blank_issues_enabled: false
contact_links:
  - name: 💼 Volume licenses
    url: mailto:info@niedermann.it
    about: If you are a company, a club, a university or another organization, please contact us directly for volume licenses.